/**
 * Steps 的静态样式（G3/G4 产物）。
 *
 * 契约来源：antd 6.6.4 的 `components/steps/style`（React SSR + `extractStyle`
 * 真实产物逐条机械转换，提取脚本 `tests/visual/debug/extract-steps.mjs`，
 * 15 个 variant 场景 SSR dump）。
 *
 * 转换规则（与 select/modal 同管线）：
 *   1. 去掉 `:where(.css-dev-only-…)` hash 前缀（静态移植无 hashId）。
 *   2. `.ant-*` → `.apollo-*`；`--ant-*` → `--apollo-*`；`.anticon` → `.apollo-icon`（D15）。
 *   3. 组件变量声明块：antd 挂在 `.css-var-…ant-steps`（死选择器，体以 `--ant-steps-*`
 *      开头）；本仓按 D69 同判落在根形态 `.apollo-steps` 上（DECLS 原序字面量）。
 *   4. at-rule（`@media`）按**块体**判据保留（modal 期教训）。
 *   5. Trigger 浮层共享动效（fade / zoom-big 的 @keyframes）不在此重复 ——
 *      `_internal/trigger` 的 motion 基线职责（dropdown 的 slide-* 同判）。
 *   6. genCssVar 交叉引用 `var(--ant-cmp-steps-…)` → `--apollo-cmp-steps-…`
 *      （定义块与消费块同在本文件，自洽；items-offset 由 Steps.ts rootStyle 注入）。
 */

/** 组件变量声明（对拍 antd 的 `.css-var-…ant-steps` 块，原序字面量）。 */
export function genStepsTokenDecls(): string {
  return DECLS;
}

const DECLS = `--apollo-steps-title-line-height:32px;--apollo-steps-custom-icon-size:32px;--apollo-steps-custom-icon-top:0px;--apollo-steps-custom-icon-font-size:24px;--apollo-steps-icon-size:32px;--apollo-steps-icon-top:-0.5px;--apollo-steps-icon-font-size:14px;--apollo-steps-icon-size-sm:24px;--apollo-steps-dot-size:8px;--apollo-steps-dot-current-size:10px;--apollo-steps-nav-arrow-color:rgba(0,0,0,0.25);--apollo-steps-nav-content-max-width:unset;--apollo-steps-wait-icon-color:rgba(0,0,0,0.65);--apollo-steps-wait-icon-bg-color:rgba(0,0,0,0.06);--apollo-steps-wait-icon-border-color:transparent;--apollo-steps-finish-icon-bg-color:#e6f4ff;--apollo-steps-finish-icon-border-color:#e6f4ff;`;

/** antd 产物机械转换段（原序）。 */
const RULES = `
.apollo-steps{font-family:var(--apollo-font-family);font-size:var(--apollo-font-size);box-sizing:border-box;}
.apollo-steps::before,.apollo-steps::after{box-sizing:border-box;}
.apollo-steps [class^="apollo-steps"],.apollo-steps [class*=" apollo-steps"]{box-sizing:border-box;}
.apollo-steps [class^="apollo-steps"]::before,.apollo-steps [class*=" apollo-steps"]::before,.apollo-steps [class^="apollo-steps"]::after,.apollo-steps [class*=" apollo-steps"]::after{box-sizing:border-box;}
.apollo-steps{--apollo-cmp-steps-title-font-size:var(--apollo-font-size-lg);--apollo-cmp-steps-title-line-height:var(--apollo-line-height-lg);--apollo-cmp-steps-subtitle-font-size:var(--apollo-font-size);--apollo-cmp-steps-subtitle-line-height:var(--apollo-line-height);--apollo-cmp-steps-item-wrapper-padding-top:0px;--apollo-cmp-steps-rail-size:var(--apollo-line-width);--apollo-cmp-steps-rail-line-style:var(--apollo-line-type);box-sizing:border-box;margin:0;padding:0;color:var(--apollo-color-text);font-size:var(--apollo-font-size);line-height:var(--apollo-line-height);list-style:none;font-family:var(--apollo-font-family);display:flex;flex-wrap:nowrap;align-items:flex-start;}
.apollo-steps .apollo-steps-item{flex:none;position:relative;}
.apollo-steps .apollo-steps-item-wrapper{display:flex;flex-wrap:nowrap;padding-top:var(--apollo-cmp-steps-item-wrapper-padding-top);}
.apollo-steps .apollo-steps-item-header{display:flex;flex-wrap:nowrap;align-items:center;}
.apollo-steps .apollo-steps-item-title{color:var(--apollo-color-text);font-size:var(--apollo-cmp-steps-title-font-size);line-height:var(--apollo-cmp-steps-title-line-height);word-break:break-word;}
.apollo-steps .apollo-steps-item-subtitle{color:var(--apollo-color-text-description);font-weight:normal;font-size:var(--apollo-cmp-steps-subtitle-font-size);line-height:var(--apollo-cmp-steps-subtitle-line-height);margin-inline-start:var(--apollo-margin-xs);word-break:break-word;}
.apollo-steps .apollo-steps-item-content{color:var(--apollo-color-text-description);font-size:var(--apollo-font-size);line-height:var(--apollo-line-height);word-break:break-word;}
.apollo-steps .apollo-steps-item-rail{border-style:var(--apollo-cmp-steps-rail-line-style);border-width:0;}
.apollo-steps .apollo-steps-item-title,.apollo-steps .apollo-steps-item-subtitle,.apollo-steps .apollo-steps-item-content,.apollo-steps .apollo-steps-item-rail{transition:all var(--apollo-motion-duration-slow);}
.apollo-steps.apollo-steps-ellipsis .apollo-steps-item-title,.apollo-steps.apollo-steps-ellipsis .apollo-steps-item-subtitle,.apollo-steps.apollo-steps-ellipsis .apollo-steps-item-content{overflow:hidden;white-space:nowrap;text-overflow:ellipsis;}
.apollo-steps .apollo-steps-item[role='button']:focus-visible{outline:var(--apollo-line-width-focus) solid var(--apollo-color-primary-border);outline-offset:1px;transition:outline-offset 0s,outline 0s;}
.apollo-steps .apollo-steps-item[role='button']:not(.apollo-steps-item-active):hover{cursor:pointer;}
.apollo-steps{--apollo-cmp-steps-icon-size:var(--apollo-steps-icon-size);--apollo-cmp-steps-icon-border-width:var(--apollo-line-width);}
.apollo-steps .apollo-steps-item-icon{width:var(--apollo-cmp-steps-icon-size);height:var(--apollo-cmp-steps-icon-size);margin:0;flex:none;display:flex;align-items:center;justify-content:center;font-size:var(--apollo-steps-icon-font-size);font-family:var(--apollo-font-family);line-height:var(--apollo-cmp-steps-icon-size);text-align:center;border-radius:var(--apollo-cmp-steps-icon-size);border:var(--apollo-cmp-steps-icon-border-width) var(--apollo-line-type) transparent;transition:background-color var(--apollo-motion-duration-slow),border var(--apollo-motion-duration-slow),color var(--apollo-motion-duration-slow),inset var(--apollo-motion-duration-slow),transform var(--apollo-motion-duration-slow);z-index:1;}
.apollo-steps .apollo-steps-item-custom .apollo-steps-item-icon{background:none;border:0;font-size:var(--apollo-steps-custom-icon-font-size);}
.apollo-steps-vertical{--apollo-cmp-steps-vertical-rail-margin:calc(var(--apollo-margin-xxs) * 1.5);flex-direction:column;align-items:stretch;}
.apollo-steps-vertical >.apollo-steps-item{min-height:calc(var(--apollo-control-height) * 1.5);padding-bottom:var(--apollo-padding-sm);}
.apollo-steps-vertical >.apollo-steps-item:last-child{padding-bottom:0;}
.apollo-steps-vertical >.apollo-steps-item .apollo-steps-item-icon{margin-inline-start:calc((var(--apollo-cmp-steps-icon-size-max) - var(--apollo-cmp-steps-icon-size)) / 2);}
.apollo-steps-vertical >.apollo-steps-item .apollo-steps-item-rail{--apollo-cmp-steps-rail-offset:calc((var(--apollo-cmp-steps-heading-height) - var(--apollo-cmp-steps-icon-size)) / 2);border-inline-start-width:var(--apollo-cmp-steps-rail-size);position:absolute;top:calc(var(--apollo-cmp-steps-icon-size) + var(--apollo-cmp-steps-item-wrapper-padding-top) + var(--apollo-cmp-steps-rail-offset) + var(--apollo-cmp-steps-vertical-rail-margin));inset-inline-start:calc(var(--apollo-cmp-steps-icon-size-max) / 2);bottom:calc(var(--apollo-cmp-steps-vertical-rail-margin) - var(--apollo-cmp-steps-rail-offset));margin-inline-start:calc(var(--apollo-cmp-steps-rail-size) / -2);}
.apollo-steps-horizontal >.apollo-steps-item{flex:1 1 auto;min-width:var(--apollo-steps-icon-size);}
.apollo-steps-horizontal >.apollo-steps-item .apollo-steps-item-rail{--apollo-cmp-steps-horizontal-rail-margin:calc(var(--apollo-cmp-steps-icon-size-max) / 2 - var(--apollo-cmp-steps-rail-size) / 2 + var(--apollo-cmp-steps-item-wrapper-padding-top));position:static;margin-top:var(--apollo-cmp-steps-horizontal-rail-margin);width:auto;border-block-start-width:var(--apollo-cmp-steps-rail-size);flex:1;min-width:0;align-self:flex-start;}
.apollo-steps{--apollo-cmp-steps-icon-size-max:max(var(--apollo-cmp-steps-icon-size), var(--apollo-cmp-steps-icon-size-active, var(--apollo-cmp-steps-icon-size)));}
.apollo-steps .apollo-steps-item-icon{margin-block-start:calc((var(--apollo-cmp-steps-heading-height) - var(--apollo-cmp-steps-icon-size)) / 2);}
.apollo-steps-title-horizontal{--apollo-cmp-steps-title-horizontal-item-margin:var(--apollo-margin);--apollo-cmp-steps-title-horizontal-rail-margin:var(--apollo-margin);--apollo-cmp-steps-title-horizontal-title-height:var(--apollo-font-height-lg);--apollo-cmp-steps-heading-height:max(var(--apollo-cmp-steps-icon-size), var(--apollo-cmp-steps-title-horizontal-title-height));}
.apollo-steps-title-horizontal.apollo-steps-horizontal .apollo-steps-item:not(:first-child),.apollo-steps-title-horizontal.apollo-steps-horizontal-alternate .apollo-steps-item:not(:first-child){margin-inline-start:var(--apollo-cmp-steps-title-horizontal-item-margin);}
.apollo-steps-title-horizontal.apollo-steps-horizontal .apollo-steps-item:last-child,.apollo-steps-title-horizontal.apollo-steps-horizontal-alternate .apollo-steps-item:last-child{flex:0 1 auto;}
.apollo-steps-title-horizontal.apollo-steps-horizontal .apollo-steps-item-wrapper,.apollo-steps-title-horizontal.apollo-steps-horizontal-alternate .apollo-steps-item-wrapper{column-gap:var(--apollo-margin-xs);}
.apollo-steps-title-horizontal.apollo-steps-vertical .apollo-steps-item-wrapper{column-gap:var(--apollo-margin);}
.apollo-steps-title-horizontal.apollo-steps-vertical .apollo-steps-item-empty-header .apollo-steps-item-header{min-height:auto;}
.apollo-steps-title-horizontal.apollo-steps-vertical .apollo-steps-item-empty-header .apollo-steps-item-content{margin-top:calc((var(--apollo-cmp-steps-heading-height) - var(--apollo-font-height)) / 2);}
.apollo-steps-title-horizontal .apollo-steps-item-section{flex:1;min-width:0;}
.apollo-steps-title-horizontal .apollo-steps-item-header{min-height:var(--apollo-cmp-steps-heading-height);}
.apollo-steps-title-horizontal .apollo-steps-item-title{flex:0 1 auto;}
.apollo-steps-title-horizontal .apollo-steps-item-content{max-width:var(--apollo-steps-description-max-width);}
.apollo-steps-title-horizontal .apollo-steps-item-subtitle{flex:0 9999 auto;}
.apollo-steps-title-horizontal.apollo-steps-horizontal .apollo-steps-item-rail{--apollo-cmp-steps-item-wrapper-padding-top:0px;flex:1 1 0%;margin-inline-start:var(--apollo-cmp-steps-title-horizontal-rail-margin);}
.apollo-steps-title-vertical{--apollo-cmp-steps-title-vertical-row-gap:var(--apollo-padding-sm);--apollo-cmp-steps-title-horizontal-rail-gap:var(--apollo-margin-xxs);--apollo-cmp-steps-heading-height:var(--apollo-cmp-steps-icon-size-max);}
.apollo-steps-title-vertical >.apollo-steps-item{flex:1 1 0%;}
.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-wrapper{flex-direction:column;row-gap:var(--apollo-cmp-steps-title-vertical-row-gap);align-items:center;}
.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-section{align-self:stretch;}
.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-header{flex-direction:column;align-items:center;}
.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-title,.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-subtitle,.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-content{text-align:center;max-width:100%;}
.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-subtitle{margin:0;}
.apollo-steps-title-vertical >.apollo-steps-item .apollo-steps-item-rail{position:absolute;top:0;width:calc(100% - var(--apollo-cmp-steps-icon-size) - var(--apollo-cmp-steps-title-horizontal-rail-gap) * 2);inset-inline-start:calc(50% + var(--apollo-cmp-steps-icon-size) / 2 + var(--apollo-cmp-steps-title-horizontal-rail-gap));}
@container style(--apollo-steps-description-max-width){.apollo-steps-title-vertical .apollo-steps-item-icon{margin-inline-start:calc((var(--apollo-steps-description-max-width) - var(--apollo-cmp-steps-icon-size)) / 2);}.apollo-steps-title-vertical .apollo-steps-item-rail{width:auto;inset-inline-start:calc((var(--apollo-steps-description-max-width) + var(--apollo-cmp-steps-icon-size)) / 2 + var(--apollo-margin-xs));inset-inline-end:calc(((var(--apollo-steps-description-max-width) - var(--apollo-cmp-steps-icon-size)) / 2 - var(--apollo-margin-xs)) * -1);}.apollo-steps-title-vertical .apollo-steps-item:last-child{flex:none;}.apollo-steps-title-vertical .apollo-steps-item-icon{align-self:flex-start;}.apollo-steps-title-vertical .apollo-steps-item-section{width:var(--apollo-steps-description-max-width);}}
.apollo-steps.apollo-steps-small{--apollo-cmp-steps-icon-size:var(--apollo-steps-icon-size-sm);--apollo-cmp-steps-title-horizontal-item-margin:var(--apollo-margin-sm);--apollo-cmp-steps-title-vertical-row-gap:var(--apollo-padding-xs);--apollo-cmp-steps-title-font-size:var(--apollo-font-size);--apollo-cmp-steps-title-line-height:var(--apollo-line-height);--apollo-cmp-steps-title-horizontal-rail-margin:var(--apollo-margin-xs);--apollo-cmp-steps-title-horizontal-title-height:var(--apollo-font-height);}
@container style(--apollo-steps-description-max-width){.apollo-steps.apollo-steps-small.apollo-steps-horizontal.apollo-steps-title-vertical .apollo-steps-item-icon{margin-inline-start:calc((var(--apollo-steps-description-max-width) - var(--apollo-cmp-steps-icon-size)) / 2);}.apollo-steps.apollo-steps-small.apollo-steps-horizontal.apollo-steps-title-vertical .apollo-steps-item-rail{width:auto;inset-inline-start:calc((var(--apollo-steps-description-max-width) + var(--apollo-cmp-steps-icon-size)) / 2 + var(--apollo-margin-xs));inset-inline-end:calc(((var(--apollo-steps-description-max-width) - var(--apollo-cmp-steps-icon-size)) / 2 - var(--apollo-margin-xs)) * -1);}}
.apollo-steps.apollo-steps-dot{--apollo-cmp-steps-icon-size-active:var(--apollo-steps-dot-current-size);--apollo-cmp-steps-icon-size:var(--apollo-steps-dot-size);--apollo-cmp-steps-dot-icon-size:var(--apollo-steps-dot-size);--apollo-cmp-steps-dot-icon-border-width:var(--apollo-line-width-bold);--apollo-cmp-steps-rail-size:var(--apollo-line-width-bold);--apollo-cmp-steps-icon-border-width:var(--apollo-line-width-bold);}
.apollo-steps.apollo-steps-dot .apollo-steps-item-custom .apollo-steps-item-icon{font-size:var(--apollo-font-size-sm);}
.apollo-steps.apollo-steps-dot .apollo-steps-item-icon{position:relative;}
.apollo-steps.apollo-steps-dot .apollo-steps-item-icon:after{content:"";width:var(--apollo-steps-icon-size);height:var(--apollo-steps-icon-size);display:block;position:absolute;top:50%;left:50%;transform:translate(-50%, -50%);}
.apollo-steps.apollo-steps-dot .apollo-steps-item-active .apollo-steps-item-icon{--apollo-cmp-steps-icon-size:var(--apollo-cmp-steps-icon-size-active);}
@container style(--apollo-steps-description-max-width){.apollo-steps.apollo-steps-dot.apollo-steps-horizontal .apollo-steps-item-icon,.apollo-steps.apollo-steps-dot.apollo-steps-horizontal.apollo-steps-small .apollo-steps-item-icon{margin-inline-start:calc((var(--apollo-steps-description-max-width) - var(--apollo-cmp-steps-icon-size)) / 2);}.apollo-steps.apollo-steps-dot.apollo-steps-horizontal .apollo-steps-item-rail,.apollo-steps.apollo-steps-dot.apollo-steps-horizontal.apollo-steps-small .apollo-steps-item-rail{width:auto;inset-inline-start:calc((var(--apollo-steps-description-max-width) + var(--apollo-cmp-steps-icon-size)) / 2 + var(--apollo-margin-xxs));inset-inline-end:calc(((var(--apollo-steps-description-max-width) - var(--apollo-cmp-steps-icon-size)) / 2 - var(--apollo-margin-xxs)) * -1);}}
.apollo-steps .apollo-steps-item{--apollo-cmp-steps-item-solid-line-color:#000;--apollo-cmp-steps-item-title-color:#000;--apollo-cmp-steps-item-content-color:#000;--apollo-cmp-steps-item-subtitle-color:var(--apollo-cmp-steps-item-content-color);--apollo-cmp-steps-item-icon-custom-color:#000;--apollo-cmp-steps-item-icon-bg-color:#000;--apollo-cmp-steps-item-icon-border-color:#000;--apollo-cmp-steps-item-icon-text-color:#fff;--apollo-cmp-steps-item-icon-dot-color:#000;--apollo-cmp-steps-item-icon-dot-bg-color:var(--apollo-cmp-steps-item-icon-dot-color);--apollo-cmp-steps-item-icon-dot-border-color:var(--apollo-cmp-steps-item-icon-dot-color);--apollo-cmp-steps-item-text-hover-color:#000;--apollo-cmp-steps-item-icon-bg-hover-color:var(--apollo-cmp-steps-item-icon-bg-color);--apollo-cmp-steps-item-icon-border-hover-color:var(--apollo-cmp-steps-item-icon-border-color);--apollo-cmp-steps-item-icon-text-hover-color:var(--apollo-cmp-steps-item-icon-text-color);--apollo-cmp-steps-item-content-active-color:var(--apollo-cmp-steps-item-content-color);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-cmp-steps-item-icon-bg-color);--apollo-cmp-steps-item-icon-active-border-color:var(--apollo-cmp-steps-item-icon-border-color);--apollo-cmp-steps-item-icon-active-text-color:var(--apollo-cmp-steps-item-icon-text-color);--apollo-cmp-steps-item-process-rail-line-style:var(--apollo-line-type);}
.apollo-steps .apollo-steps-item-rail{border-color:var(--apollo-cmp-steps-item-solid-line-color);}
.apollo-steps .apollo-steps-item-custom .apollo-steps-item-icon{color:var(--apollo-cmp-steps-item-icon-custom-color);}
.apollo-steps .apollo-steps-item-title{color:var(--apollo-cmp-steps-item-title-color);}
.apollo-steps .apollo-steps-item-subtitle{color:var(--apollo-cmp-steps-item-subtitle-color);}
.apollo-steps .apollo-steps-item-content{color:var(--apollo-cmp-steps-item-content-color);}
.apollo-steps .apollo-steps-item-active .apollo-steps-item-content{color:var(--apollo-cmp-steps-item-content-active-color);}
.apollo-steps .apollo-steps-item[role='button']:not(.apollo-steps-item-active):hover .apollo-steps-item-title,.apollo-steps .apollo-steps-item[role='button']:not(.apollo-steps-item-active):hover .apollo-steps-item-content{color:var(--apollo-cmp-steps-item-text-hover-color);}
.apollo-steps:not(.apollo-steps-dot) .apollo-steps-item:not(.apollo-steps-item-custom) .apollo-steps-item-icon{background:var(--apollo-cmp-steps-item-icon-bg-color);border-color:var(--apollo-cmp-steps-item-icon-border-color);color:var(--apollo-cmp-steps-item-icon-text-color);}
.apollo-steps:not(.apollo-steps-dot) .apollo-steps-item:not(.apollo-steps-item-custom)[role='button']:not(.apollo-steps-item-active):hover .apollo-steps-item-icon{background:var(--apollo-cmp-steps-item-icon-bg-hover-color);border-color:var(--apollo-cmp-steps-item-icon-border-hover-color);color:var(--apollo-cmp-steps-item-icon-text-hover-color);}
.apollo-steps:not(.apollo-steps-dot) .apollo-steps-item:not(.apollo-steps-item-custom).apollo-steps-item-active .apollo-steps-item-icon{background:var(--apollo-cmp-steps-item-icon-active-bg-color);border-color:var(--apollo-cmp-steps-item-icon-active-border-color);color:var(--apollo-cmp-steps-item-icon-active-text-color);}
.apollo-steps.apollo-steps-dot .apollo-steps-item-icon{background:var(--apollo-cmp-steps-item-icon-dot-bg-color);border-color:var(--apollo-cmp-steps-item-icon-dot-border-color);color:var(--apollo-cmp-steps-item-icon-dot-color);}
.apollo-steps.apollo-steps-dot .apollo-steps-item-icon.apollo-steps-item-icon-dot-custom{background:transparent;border:none;}
.apollo-steps .apollo-steps-item-wait{--apollo-cmp-steps-item-icon-custom-color:var(--apollo-color-text-disabled);--apollo-cmp-steps-item-title-color:var(--apollo-color-text-description);--apollo-cmp-steps-item-content-color:var(--apollo-color-text-description);--apollo-cmp-steps-item-content-active-color:var(--apollo-color-text);--apollo-cmp-steps-item-text-hover-color:var(--apollo-color-primary-hover);}
.apollo-steps .apollo-steps-item-rail-wait{--apollo-cmp-steps-item-solid-line-color:var(--apollo-color-text-disabled);}
.apollo-steps .apollo-steps-item-process{--apollo-cmp-steps-item-icon-custom-color:var(--apollo-color-primary);--apollo-cmp-steps-item-title-color:var(--apollo-color-text);--apollo-cmp-steps-item-content-color:var(--apollo-color-text-description);--apollo-cmp-steps-item-content-active-color:var(--apollo-color-text);--apollo-cmp-steps-item-text-hover-color:var(--apollo-color-primary-hover);}
.apollo-steps .apollo-steps-item-rail-process{--apollo-cmp-steps-item-solid-line-color:var(--apollo-color-primary);--apollo-cmp-steps-rail-line-style:var(--apollo-cmp-steps-item-process-rail-line-style);}
.apollo-steps .apollo-steps-item-finish{--apollo-cmp-steps-item-icon-custom-color:var(--apollo-color-primary);--apollo-cmp-steps-item-title-color:var(--apollo-color-text);--apollo-cmp-steps-item-content-color:var(--apollo-color-text-description);--apollo-cmp-steps-item-content-active-color:var(--apollo-color-text);--apollo-cmp-steps-item-text-hover-color:var(--apollo-color-primary-hover);}
.apollo-steps .apollo-steps-item-rail-finish{--apollo-cmp-steps-item-solid-line-color:var(--apollo-color-primary);}
.apollo-steps .apollo-steps-item-error{--apollo-cmp-steps-item-icon-custom-color:var(--apollo-color-error);--apollo-cmp-steps-item-title-color:var(--apollo-color-error);--apollo-cmp-steps-item-content-color:var(--apollo-color-error);--apollo-cmp-steps-item-content-active-color:var(--apollo-color-error);--apollo-cmp-steps-item-text-hover-color:var(--apollo-color-error-hover);}
.apollo-steps .apollo-steps-item-rail-error{--apollo-cmp-steps-item-solid-line-color:var(--apollo-color-error);}
.apollo-steps.apollo-steps-filled .apollo-steps-item{--apollo-cmp-steps-item-icon-dot-border-color:transparent;}
.apollo-steps.apollo-steps-filled .apollo-steps-item-wait{--apollo-cmp-steps-item-icon-bg-color:var(--apollo-color-fill-tertiary);--apollo-cmp-steps-item-icon-border-color:transparent;--apollo-cmp-steps-item-icon-text-color:var(--apollo-color-text-label);--apollo-cmp-steps-item-icon-dot-bg-color:var(--apollo-color-text-disabled);--apollo-cmp-steps-item-icon-bg-hover-color:var(--apollo-color-primary-bg-hover);--apollo-cmp-steps-item-icon-border-hover-color:transparent;--apollo-cmp-steps-item-icon-text-hover-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-active-border-color:transparent;--apollo-cmp-steps-item-icon-active-text-color:var(--apollo-color-text-light-solid);}
.apollo-steps.apollo-steps-filled .apollo-steps-item-process,.apollo-steps.apollo-steps-filled .apollo-steps-item-finish{--apollo-cmp-steps-item-icon-bg-color:var(--apollo-color-primary-bg);--apollo-cmp-steps-item-icon-border-color:transparent;--apollo-cmp-steps-item-icon-text-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-dot-bg-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-bg-hover-color:var(--apollo-color-primary-bg-hover);--apollo-cmp-steps-item-icon-border-hover-color:transparent;--apollo-cmp-steps-item-icon-text-hover-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-active-border-color:transparent;--apollo-cmp-steps-item-icon-active-text-color:var(--apollo-color-text-light-solid);}
.apollo-steps.apollo-steps-filled .apollo-steps-item-error{--apollo-cmp-steps-item-icon-bg-color:var(--apollo-color-error-bg);--apollo-cmp-steps-item-icon-border-color:transparent;--apollo-cmp-steps-item-icon-text-color:var(--apollo-color-error);--apollo-cmp-steps-item-icon-dot-bg-color:var(--apollo-color-error);--apollo-cmp-steps-item-icon-bg-hover-color:var(--apollo-color-error-bg-filled-hover);--apollo-cmp-steps-item-icon-border-hover-color:transparent;--apollo-cmp-steps-item-icon-text-hover-color:var(--apollo-color-error);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-color-error);--apollo-cmp-steps-item-icon-active-border-color:transparent;--apollo-cmp-steps-item-icon-active-text-color:var(--apollo-color-text-light-solid);}
.apollo-steps.apollo-steps-outlined .apollo-steps-item{--apollo-cmp-steps-item-icon-dot-bg-color:transparent;}
.apollo-steps.apollo-steps-outlined .apollo-steps-item-wait{--apollo-cmp-steps-item-icon-bg-color:var(--apollo-color-bg-container);--apollo-cmp-steps-item-icon-border-color:var(--apollo-color-text-disabled);--apollo-cmp-steps-item-icon-text-color:var(--apollo-color-text-disabled);--apollo-cmp-steps-item-icon-dot-color:var(--apollo-color-text-disabled);--apollo-cmp-steps-item-icon-bg-hover-color:transparent;--apollo-cmp-steps-item-icon-border-hover-color:var(--apollo-color-primary-hover);--apollo-cmp-steps-item-icon-text-hover-color:var(--apollo-color-primary-hover);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-color-fill-tertiary);}
.apollo-steps.apollo-steps-outlined .apollo-steps-item-process,.apollo-steps.apollo-steps-outlined .apollo-steps-item-finish{--apollo-cmp-steps-item-icon-bg-color:var(--apollo-color-bg-container);--apollo-cmp-steps-item-icon-border-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-text-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-dot-color:var(--apollo-color-primary);--apollo-cmp-steps-item-icon-bg-hover-color:transparent;--apollo-cmp-steps-item-icon-border-hover-color:var(--apollo-color-primary-hover);--apollo-cmp-steps-item-icon-text-hover-color:var(--apollo-color-primary-hover);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-color-primary-bg);}
.apollo-steps.apollo-steps-outlined .apollo-steps-item-error{--apollo-cmp-steps-item-icon-bg-color:var(--apollo-color-bg-container);--apollo-cmp-steps-item-icon-border-color:var(--apollo-color-error);--apollo-cmp-steps-item-icon-text-color:var(--apollo-color-error);--apollo-cmp-steps-item-icon-dot-color:var(--apollo-color-error);--apollo-cmp-steps-item-icon-bg-hover-color:transparent;--apollo-cmp-steps-item-icon-border-hover-color:var(--apollo-color-error-hover);--apollo-cmp-steps-item-icon-text-hover-color:var(--apollo-color-error-hover);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-color-error-bg);}
.apollo-steps.apollo-steps-navigation .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item{display:flex;justify-content:center;position:relative;flex:1;margin-inline-start:0;}
.apollo-steps.apollo-steps-navigation .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item .apollo-steps-item-wrapper{padding-block:var(--apollo-padding-sm);}
.apollo-steps.apollo-steps-navigation .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item .apollo-steps-item-section{max-width:var(--apollo-steps-nav-content-max-width);}
.apollo-steps.apollo-steps-navigation .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item .apollo-steps-item-rail{display:none;}
.apollo-steps.apollo-steps-navigation .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item:before{position:absolute;display:block;background-color:var(--apollo-color-primary);transition:all var(--apollo-motion-duration-slow);transition-timing-function:ease-out;content:"";}
.apollo-steps.apollo-steps-navigation .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item:not(:last-child):after{position:absolute;display:block;border-top:var(--apollo-line-width) var(--apollo-line-type) var(--apollo-steps-nav-arrow-color);border-bottom:none;border-inline-start:none;border-inline-end:var(--apollo-line-width) var(--apollo-line-type) var(--apollo-steps-nav-arrow-color);content:"";}
.apollo-steps.apollo-steps-navigation .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item-active{--apollo-cmp-steps-item-content-active-color:var(--apollo-cmp-steps-item-content-color);--apollo-cmp-steps-item-icon-active-bg-color:var(--apollo-cmp-steps-item-icon-bg-color);--apollo-cmp-steps-item-icon-active-border-color:var(--apollo-cmp-steps-item-icon-border-color);--apollo-cmp-steps-item-icon-active-text-color:var(--apollo-cmp-steps-item-icon-text-color);}
.apollo-steps.apollo-steps-navigation.apollo-steps-horizontal .apollo-steps-item:before{bottom:0;inset-inline-start:50%;width:0;height:var(--apollo-line-width-bold);}
.apollo-steps.apollo-steps-navigation.apollo-steps-horizontal .apollo-steps-item.apollo-steps-item-active:before{inset-inline-start:0;width:100%;}
.apollo-steps.apollo-steps-navigation.apollo-steps-horizontal .apollo-steps-item:not(:last-child):after{top:50%;inset-inline-start:calc(var(--apollo-font-size-icon) / 2 * -1 + 100%);width:var(--apollo-font-size-icon);height:var(--apollo-font-size-icon);transform:translateY(-50%) rotate(45deg);}
.apollo-steps.apollo-steps-navigation.apollo-steps-vertical .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item .apollo-steps-item-content{padding:0;}
.apollo-steps.apollo-steps-navigation.apollo-steps-vertical .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item:before{inset-inline-end:0;top:50%;width:var(--apollo-line-width-bold);height:0;}
.apollo-steps.apollo-steps-navigation.apollo-steps-vertical .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item-active::before{top:0;height:100%;}
.apollo-steps.apollo-steps-navigation.apollo-steps-vertical .apollo-steps-item.apollo-steps-item.apollo-steps-item.apollo-steps-item:not(:last-child):after{left:50%;top:100%;width:calc(var(--apollo-font-size-icon) / 3 * 2);height:calc(var(--apollo-font-size-icon) / 3 * 2);transform:translateY(-50%) translateX(-50%) rotate(135deg);}
.apollo-steps.apollo-steps-panel .apollo-steps-item-rail{display:none;}
.apollo-steps.apollo-steps-panel.apollo-steps-horizontal{align-items:stretch;}
.apollo-steps.apollo-steps-panel.apollo-steps-horizontal .apollo-steps-item{flex:1;margin:0;}
.apollo-steps.apollo-steps-panel{--apollo-cmp-steps-panel-padding:var(--apollo-padding-sm);--apollo-cmp-steps-item-border-radius:var(--apollo-border-radius);}
.apollo-steps.apollo-steps-panel .apollo-steps-item{--apollo-cmp-steps-panel-bg-color:var(--apollo-cmp-steps-item-icon-bg-color);--apollo-cmp-steps-panel-border-color:var(--apollo-cmp-steps-item-icon-border-color);--apollo-cmp-steps-panel-active-bg-color:var(--apollo-cmp-steps-item-icon-active-bg-color);--apollo-cmp-steps-panel-active-border-color:var(--apollo-cmp-steps-item-icon-active-border-color);--apollo-cmp-steps-panel-title-height:calc(var(--apollo-cmp-steps-title-font-size) * var(--apollo-cmp-steps-title-line-height));--apollo-cmp-steps-item-base-height:calc(var(--apollo-cmp-steps-panel-padding) * 2 + var(--apollo-cmp-steps-icon-size) + var(--apollo-cmp-steps-panel-title-height));--apollo-cmp-steps-item-base-width:calc(var(--apollo-cmp-steps-item-base-height) * 0.7071);transition:background-color var(--apollo-motion-duration-mid);}
.apollo-steps.apollo-steps-panel .apollo-steps-item-icon{display:none;}
.apollo-steps.apollo-steps-panel .apollo-steps-item-header{min-height:auto;}
.apollo-steps.apollo-steps-panel .apollo-steps-panel-arrow{position:absolute;top:calc(var(--apollo-line-width-bold) * -1);inset-inline-start:100%;z-index:1;height:calc(var(--apollo-line-width-bold) * 2 + 100%);width:var(--apollo-cmp-steps-item-base-width);overflow:visible;stroke-linecap:round;}
.apollo-steps.apollo-steps-panel .apollo-steps-panel-arrow path{fill:var(--apollo-cmp-steps-panel-bg-color);stroke:var(--apollo-cmp-steps-panel-border-color);stroke-width:var(--apollo-line-width-bold);vector-effect:non-scaling-stroke;transition:fill var(--apollo-motion-duration-mid);}
.apollo-steps.apollo-steps-panel .apollo-steps-item:last-child .apollo-steps-panel-arrow{display:none;}
.apollo-steps.apollo-steps-panel .apollo-steps-item{padding:var(--apollo-cmp-steps-panel-padding);background:var(--apollo-cmp-steps-panel-bg-color);position:relative;border-block:var(--apollo-line-width-bold) var(--apollo-line-type) var(--apollo-cmp-steps-panel-border-color);}
.apollo-steps.apollo-steps-panel .apollo-steps-item:not(:first-child){padding-inline-start:calc(var(--apollo-cmp-steps-panel-padding) + var(--apollo-cmp-steps-item-base-width));}
.apollo-steps.apollo-steps-panel .apollo-steps-item:first-child{border-inline-start:var(--apollo-line-width-bold) var(--apollo-line-type) var(--apollo-cmp-steps-panel-border-color);border-start-start-radius:var(--apollo-cmp-steps-item-border-radius);border-end-start-radius:var(--apollo-cmp-steps-item-border-radius);}
.apollo-steps.apollo-steps-panel .apollo-steps-item:last-child{border-inline-end:var(--apollo-line-width-bold) var(--apollo-line-type) var(--apollo-cmp-steps-panel-border-color);border-start-end-radius:var(--apollo-cmp-steps-item-border-radius);border-end-end-radius:var(--apollo-cmp-steps-item-border-radius);}
.apollo-steps.apollo-steps-panel .apollo-steps-item-active{background:var(--apollo-cmp-steps-panel-active-bg-color);border-color:var(--apollo-cmp-steps-panel-active-border-color);}
.apollo-steps.apollo-steps-panel .apollo-steps-item-active .apollo-steps-panel-arrow path{fill:var(--apollo-cmp-steps-panel-active-bg-color);stroke:var(--apollo-cmp-steps-panel-active-border-color);}
.apollo-steps.apollo-steps-panel .apollo-steps-item-active .apollo-steps-item-title,.apollo-steps.apollo-steps-panel .apollo-steps-item-active .apollo-steps-item-subtitle,.apollo-steps.apollo-steps-panel .apollo-steps-item-active .apollo-steps-item-content{color:var(--apollo-cmp-steps-item-icon-active-text-color);}
.apollo-steps.apollo-steps-panel.apollo-steps-small{--apollo-cmp-steps-panel-padding:var(--apollo-padding-xs);--apollo-cmp-steps-item-border-radius:var(--apollo-border-radius-sm);}
.apollo-steps.apollo-steps-panel.apollo-steps-filled .apollo-steps-item:not(:first-child){clip-path:polygon(var(--apollo-line-width-bold) 0,calc(100% + var(--apollo-cmp-steps-item-base-width)) 0,calc(100% + var(--apollo-cmp-steps-item-base-width)) 100%,var(--apollo-line-width-bold) 100%,calc(var(--apollo-cmp-steps-item-base-width) + var(--apollo-line-width-bold)) 50%);}
.apollo-steps.apollo-steps-panel.apollo-steps-outlined .apollo-steps-panel-arrow{top:calc(var(--apollo-line-width-bold) / 2 * -1);height:calc(var(--apollo-line-width-bold) + 100%);}
.apollo-steps-inline{--apollo-cmp-steps-items-offset:0;--apollo-cmp-steps-item-wrapper-padding-top:calc(var(--apollo-padding-xs) + var(--apollo-line-width));display:inline-flex;}
.apollo-steps-inline:before{content:"";flex:var(--apollo-cmp-steps-items-offset);}
.apollo-steps-inline .apollo-steps-item{--apollo-cmp-steps-title-vertical-row-gap:var(--apollo-padding-xs);--apollo-cmp-steps-icon-size:6px;--apollo-cmp-steps-icon-size-active:6px;--apollo-cmp-steps-title-font-size:var(--apollo-font-size-sm);--apollo-cmp-steps-title-line-height:var(--apollo-line-height-sm);--apollo-cmp-steps-item-title-color:var(--apollo-color-text-secondary);--apollo-cmp-steps-subtitle-font-size:var(--apollo-font-size-sm);--apollo-cmp-steps-subtitle-line-height:var(--apollo-line-height-sm);--apollo-cmp-steps-item-subtitle-color:var(--apollo-color-text-quaternary);--apollo-cmp-steps-rail-size:var(--apollo-line-width);--apollo-cmp-steps-title-horizontal-rail-gap:0px;flex:1;}
.apollo-steps-inline .apollo-steps-item-wrapper{padding-inline:var(--apollo-padding-xxs);margin-inline:calc(var(--apollo-margin-xxs) / 2);border-radius:var(--apollo-border-radius-sm);cursor:pointer;transition:background-color var(--apollo-motion-duration-mid);}
.apollo-steps-inline .apollo-steps-item-wrapper:hover{background:var(--apollo-control-item-bg-hover);}
.apollo-steps-inline .apollo-steps-item-icon .apollo-steps-item-icon-dot:after{display:none;}
.apollo-steps-inline .apollo-steps-item-title{font-weight:normal;white-space:nowrap;}
.apollo-steps-inline .apollo-steps-item-content{display:none;}
.apollo-steps-max-count .apollo-steps-item-ellipsis .apollo-steps-item-title,.apollo-steps-max-count .apollo-steps-item-ellipsis .apollo-steps-item-subtitle,.apollo-steps-max-count .apollo-steps-item-ellipsis .apollo-steps-item-content{color:var(--apollo-color-text-description);}
.apollo-steps.apollo-steps-with-progress{--apollo-cmp-steps-item-wrapper-padding-top:calc(var(--apollo-line-width-bold) + var(--apollo-line-width-bold));}
.apollo-steps.apollo-steps-with-progress .apollo-steps-item.apollo-steps-item-process .apollo-steps-item-icon{position:relative;}
.apollo-steps.apollo-steps-with-progress .apollo-steps-item-progress-icon-svg{--apollo-cmp-steps-svg-size:calc(calc(var(--apollo-line-width-bold) + var(--apollo-line-width-bold)) * 2 + var(--apollo-cmp-steps-icon-size));--apollo-cmp-steps-icon-size-ptg-unitless:calc(100 / tan(atan2(var(--apollo-cmp-steps-svg-size), 1px)));font-size:var(--apollo-cmp-steps-svg-size);line-height:var(--apollo-cmp-steps-icon-size-ptg-unitless);position:absolute;inset:calc(calc(var(--apollo-line-width-bold) + var(--apollo-line-width-bold)) * -1);width:auto;height:auto;}
.apollo-steps.apollo-steps-with-progress .apollo-steps-item-progress-icon-circle{line-height:var(--apollo-cmp-steps-icon-size-ptg-unitless);stroke-width:calc(var(--apollo-cmp-steps-icon-size-ptg-unitless) * var(--apollo-line-width-bold));--apollo-cmp-steps-progress-radius:calc((var(--apollo-cmp-steps-svg-size) - var(--apollo-line-width-bold)) * var(--apollo-cmp-steps-icon-size-ptg-unitless) / 2);r:var(--apollo-cmp-steps-progress-radius);fill:none;cx:50px;cy:50px;transition:all var(--apollo-motion-duration-slow) ease-in-out;}
.apollo-steps.apollo-steps-with-progress .apollo-steps-item-progress-icon-circle-rail{stroke:var(--apollo-color-split);}
.apollo-steps.apollo-steps-with-progress .apollo-steps-item-progress-icon-circle-ptg{stroke:var(--apollo-color-primary);}
.apollo-steps.apollo-steps-rtl{direction:rtl;}
.apollo-steps.apollo-steps-rtl.apollo-steps-navigation.apollo-steps-horizontal .apollo-steps-item:after{transform:translateY(-50%) rotate(-45deg);}
.apollo-steps.apollo-steps-rtl.apollo-steps-panel .apollo-steps-panel-arrow{transform:scaleX(-1);}
.apollo-steps.apollo-steps-rtl.apollo-steps-panel.apollo-steps-filled .apollo-steps-item:not(:first-child){clip-path:polygon(calc(0px - var(--apollo-cmp-steps-item-base-width)) 0px,calc(100% - var(--apollo-line-width-bold)) 0px,calc(100% - var(--apollo-cmp-steps-item-base-width) - var(--apollo-line-width-bold)) 50%,calc(100% - var(--apollo-line-width-bold)) 100%,calc(0px - var(--apollo-cmp-steps-item-base-width)) 100%);}
`;

/** 生成单个前缀下的完整样式。 */
export function genStepsStyle(prefixCls: string = 'apollo'): string {
  const rename = (cssText: string): string =>
    prefixCls === 'apollo' ? cssText : cssText.split('.apollo-steps').join(`.${prefixCls}-steps`);
  const decls =
    prefixCls === 'apollo' ? `.apollo-steps{${DECLS}}` : `.${prefixCls}-steps{${DECLS}}`;
  return `${decls}
${rename(RULES)}`;
}
